version: 2
jobs:
 build:
  working_directory: ~/WebAppDjango
  docker:
   - image: circleci/python:3.7.0
  steps:
   - checkout
   - run:
      command: |
       sudo pip install pipenv
       pipenv install
       pipenv install django
       pipenv install PyMySQL
       pipenv run python manage.py test
   - store_test_results:
      path: test-results
   - store_artifacts:
      path: test-results
      destination: tr1 
