version: 2
jobs:
 build:
  working_directory: ~/WebAppDjango
  docker:
   - image: circleci/python:3.7.0
  steps:
   - checkout
   - run:
      command: |
       sudo pip install pipenv
       pip3 install django==2.1.8
       pip3 install PyMySQL
       python3 manage.py test
   - store_test_results:
      path: test-results
   - store_artifacts:
      path: test-results
      destination: tr1 
